// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzYvZCrqawUdgWS_OF6TKVC1E78B9LApY',
    appId: '1:333957326378:web:a6d0ff2ee02cd3a6638553',
    messagingSenderId: '333957326378',
    projectId: 'flutterstudentapp-3d00c',
    authDomain: 'flutterstudentapp-3d00c.firebaseapp.com',
    storageBucket: 'flutterstudentapp-3d00c.firebasestorage.app',
    measurementId: 'G-RWF5Q52ER8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCogXd1qihRMK7SJQtgbM3hqmSdMGRRt7k',
    appId: '1:333957326378:android:c4c832a4b42fb48d638553',
    messagingSenderId: '333957326378',
    projectId: 'flutterstudentapp-3d00c',
    storageBucket: 'flutterstudentapp-3d00c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPneUodue5QQXk1NNvblIofspTso-TwXE',
    appId: '1:333957326378:ios:044128bccca5372a638553',
    messagingSenderId: '333957326378',
    projectId: 'flutterstudentapp-3d00c',
    storageBucket: 'flutterstudentapp-3d00c.firebasestorage.app',
    iosBundleId: 'com.example.studentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPneUodue5QQXk1NNvblIofspTso-TwXE',
    appId: '1:333957326378:ios:044128bccca5372a638553',
    messagingSenderId: '333957326378',
    projectId: 'flutterstudentapp-3d00c',
    storageBucket: 'flutterstudentapp-3d00c.firebasestorage.app',
    iosBundleId: 'com.example.studentApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzYvZCrqawUdgWS_OF6TKVC1E78B9LApY',
    appId: '1:333957326378:web:b760b1b192a48860638553',
    messagingSenderId: '333957326378',
    projectId: 'flutterstudentapp-3d00c',
    authDomain: 'flutterstudentapp-3d00c.firebaseapp.com',
    storageBucket: 'flutterstudentapp-3d00c.firebasestorage.app',
    measurementId: 'G-YEXHRPVB7N',
  );
}
